spring.application.name=company-service

# Bu servis 8081 portunda çalışacak (demo 8080'de)
server.port=8081

# H2 veritabanı ayarları
spring.datasource.url=jdbc:h2:mem:companydb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop